### ISSUE TITLE
polls test

### ISSUE THREAD

**Issue by Balinus** [Balinus/ClimateTools.jl#111]
[![](https://api.gh-polls.com/poll/01DY0JK3F099JF9ES8TBZP7F9H/Option1)](https://api.gh-polls.com/poll/01DY0JK3F099JF9ES8TBZP7F9H/Option1/vote)
[![](https://api.gh-polls.com/poll/01DY0JK3F099JF9ES8TBZP7F9H/Option%202)](https://api.gh-polls.com/poll/01DY0JK3F099JF9ES8TBZP7F9H/Option%202/vote)
[![](https://api.gh-polls.com/poll/01DY0JK3F099JF9ES8TBZP7F9H/Option%203)](https://api.gh-polls.com/poll/01DY0JK3F099JF9ES8TBZP7F9H/Option%203/vote)

**Comment by ali-ramadhan** [comment]
Oh cool, didn't know about the polls bot!

Interesting that the same person/IP can keep voting for the same option multiple times haha.

**Comment by Balinus** [comment]
hehe! 

Didn't knew that. I thought it was based on https://github.com/apex/gh-polls where it states that only a single vote / IP is possible.
