### ISSUE TITLE
merge() should have option to ensure temporal consistency

### ISSUE THREAD

**Issue by Zeitsperre** [Balinus/ClimateTools.jl#12]
As we discovered earlier, a feature/bug that can occur when looping through NetCDFs is that datetime variables are not respected. ie:

merge(file2017, file2018): Dates following 2017 (Jan-Dec) -> 2018 (Jan-Dec)
and 
merge(file2018, file2017): dates following 2018 (Jan-Dec) -> 2017 (Jan-Dec)

I can't think of a reason for wanting the second option, but maybe an internal check ("time_consistency"?) that defaults to boolean true and launches a method ensuring that data sets follow each other would be a good addition. I can see it being useful for merging badly named datasets or for instances of merging data from different projects (again, not sure why one would do that but anyway).

**Comment by Balinus** [comment]
Indeed, thanks for the report! I would tend to force time consistency, but I guess that using a keyword argument defaulting to true might be enough and give the user more flexibility.

Merging data from different project wouldn't be a good idea though. For instance, the grid would not be consistent. Anyway, the user can simply extract a given model X, interpolate to grid model Y and then merge with the destination grid values already.

**Comment by Balinus** [comment]
Upstream issue https://github.com/JuliaArrays/AxisArrays.jl/issues/135

**Comment by Balinus** [comment]
used a trick here until upstream bug is resolved. https://github.com/Balinus/ClimateTools.jl/commit/4a7d8b66c39a34b2089258c48fbe1294991ed494
