### ISSUE TITLE
CF-Compliance for NetCDFs

### ISSUE THREAD

**Issue by Zeitsperre** [Balinus/ClimateTools.jl#15]
Running into some issues loading data, issues arise with definitions of CF-Compliance: https://github.com/Balinus/ClimateTools.jl/blob/653a6275060eeaf988815b024f04572da07ef6e8/src/extract.jl#L31

The "project" convention is typical for most of the grids derived from models, but this isn't part of the CF standards (http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html; abridged version: https://daac.ornl.gov/submit/netcdfrequirements/). This is particularly important for analyzing reanalysis and raw data that doesn't typically have a "project" defined.

Perhaps including a warning when the files break CF-Compliance would be good? From my understanding the only global attribute fields required are "Conventions" (with capital 'C'), "institution", "references", "title", "source", and sometimes "climatology_bounds" for normal calculations.

**Comment by Balinus** [comment]
Ok, we'll perhaps change the behaviour. However, what kind of issue do you have? The default value for `project_id()` is "NA" and lacking a project_id should not arise issue in loading the data. Which files is generating the issue?

I agree on the warning. I guess the correct place to do it would be directly in the `insittution_id` etc functions.

**Comment by Zeitsperre** [comment]
MethodError: no method matching get(::NCDatasets.Attributes, ::String, ::String)
Closest candidates are:
  get(::ObjectIdDict, ::ANY, ::ANY) at associative.jl:434
  get(::Base.EnvHash, ::AbstractString, ::Any) at env.jl:79
  get(::PyCall.PyObject, ::Any, ::Any) at /home/tjs/.julia/v0.6/PyCall/src/PyCall.jl:718
  ...
#nc2julia#104(::Array{Any,1}, ::Date, ::Date, ::String, ::Function, ::String, ::String) at extract.jl:31
nc2julia(::String, ::String) at extract.jl:22
include_string(::String, ::String) at loading.jl:522
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##102#107{String,Int64,String})() at eval.jl:82
withpath(::Atom.##102#107{String,Int64,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
hideprompt(::Atom.##101#106{String,Int64,String}) at repl.jl:67
macro expansion at eval.jl:80 [inlined]
(::Atom.##100#105{Dict{String,Any}})() at task.jl:80

**Comment by Balinus** [comment]
What's your version of NCDatasets?

`Pkg.status("NCDatasets")`

**Comment by Zeitsperre** [comment]
The error that was preventing me from loading files has been dealt with using conventional methods (needed to "turn it off and on again"). All good there.

Ensuring that the datasets are true CF-Compliant (ie: 1.5, 1.6, 1.7) would be good though. Something I can look into in the coming months maybe.

**Comment by njdepsky** [comment]
There are also issues loading netCDF data from the ECWMF/Copernicus Climate Data Store (e.g. ERA-5 reanalysis data), which supposedly is CF-1.6 compliant.  The variable string names for lat/lon in these .nc files are "latitude" and "longitude" instead of "lat", "lon" as specific in ClimateTools.load(): 

`latunits = ds["lat"].attrib["units"]`
`lonunits = ds["lon"].attrib["units"]`

Perhaps adding some try-catch functionality for both string types in the load function could make it more robust to handling "latitude"/"longitude" strings.  As it stands now the function crashes at the above commands.

**Comment by Balinus** [comment]
Thanks! Will add the proper try/catch next monday. Thanks for the report!

**Comment by Balinus** [comment]
I think that we are almost there on this issue. I'll close, we'll just open new issues as new problem arises.

**Comment by njdepsky** [comment]
Great sounds good, thanks again.
