### ISSUE TITLE
Support for climatologies

### ISSUE THREAD

**Issue by Zeitsperre** [Balinus/ClimateTools.jl#18]
Tried loading a few climatologies from netCDF and run into an issue with date incrementation. The example below is a climatology of 12 months for the normal period of 2041 to 2070. From `ncdump`:

`dimensions:`
	`time = UNLIMITED ; // (12 currently)
	lat = 3085 ;
	lon = 7747 ;`
`variables:`
	`int time(time) ;
		time:axis = "T" ;
		time:units = "months since 2055-1-1" ;
		time:long_name = "Time" ;
		time:standard_name = "time" ;
		time:calendar = "standard" ;
		time:climatology = "climatology_bounds" ;
		time:climo_period = "2041/01/01 - 2070/12/31" ;`
	`double climatology_bounds ;`
	`float lat(lat) ;
		lat:axis = "Y" ;
		lat:units = "degrees_north" ;
		lat:long_name = "latitude" ;
		lat:standard_name = "latitude" ;`
	`float lon(lon) ;
		lon:axis = "X" ;
		lon:units = "degrees_east" ;
		lon:long_name = "longitude" ;
		lon:standard_name = "longitude" ;`
	`float tasmax(time, lat, lon) ;
		tasmax:_FillValue = -9999.f ;
		tasmax:units = "deg C" ;
		tasmax:long_name = "Maximum Air Temperature" ;
		tasmax:standard_name = "max_air_temperature" ;
		tasmax:cell_methods = "time: mean over years" ;
		tasmax:comments = "Monthly average as calculated across the climatology." ;`
		
`:time = "2055-1-15 2055-2-15 2055-3-15 2055-4-152055-5-152055-6-152055-7-152055-8-15 2055-9-15 2055-10-15 2055-11-152055-12-15" ;`
`:climatology_bounds = "2055-1-1 2055-1-31 2055-2-1 2055-2-28 2055-3-1 2055-3-31 2055-4-1 2055-4-30 2055-5-1 2055-5-31 2055-6-1 2055-6-30 2055-7-1 2055-7-31 2055-8-1 2055-8-31 2055-9-1 2055-9-31 2055-10-1 2055-10-31 2055-11-1 2055-11-30 2055-12-1 2055-12-31"`

On load, it seems to be read as days starting from Jan 1, 2055. 

> ClimGrid struct with data:
   3-dimensional AxisArray{Float32,3,...} with axes:
    :time, Date[2055-01-01, 2055-01-02, 2055-01-03, 2055-01-04, 2055-01-05, 2055-01-06, 2055-01-07, 2055-01-08, 2055-01-09, 2055-01-10, 2055-01-11, 2055-01-12]

Is this  a matter of needing to include support for when `time:units` is "months"?

**Comment by Balinus** [comment]
Indeed. The function 'buildtimevector' should be defined for multiple "time resolution". Right now it assumes daily values. Clearly, a generalization should be implemented here.
Thanks fir the report!

**Comment by Balinus** [comment]
Can you retry with your test file? A lot of things have changed since then and I'm wondering if it works now, as there has been a lot of generalization on the time axis building tools.

**Comment by Balinus** [comment]
@Zeitsperre Can you send me your file? I'll test it out to see if that works now (I think so!).

**Comment by Balinus** [comment]
So without new information I'll close this one. I'm confident that this is resolved now that the Dates are handled by NCDatasets.jl (and no longer by a custom-hack!).
