### ISSUE TITLE
See GMT.jl - Integrate GMT for GRIB access

### ISSUE THREAD

**Issue by joa-quim** [Balinus/ClimateTools.jl#2]
I think you might be interested in [GMT.jl](https://github.com/joa-quim/GMT.jl). For example it already provides GRIB access (the one provided by the GDAL lib) as well as a generic netCDF grids read/write.

**Comment by Balinus** [comment]
Thanks!

It was on my list to check out GMT.jl. I was waiting for the new version actually 5.3.x (end of september?) before digging into this path. I see that it's now using the new GMT. Nice!

About GRIB access and netCDF read/write, how could I integrate it into ClimateTools? I guess the easiest would be to include GMT directly in my module (e.g. `using GMT`), but does the user absolutely needs the GMT library installed for that?

**Comment by joa-quim** [comment]
Yes, a GMT full installation is needed in order to GMT.jl to work (it has to be, the GMT lib has a set of internal interfaces to make this package, as well as a Matlab one, to work). Than you would do

```
using GMT
G = gmt("read -Tg your_grid.nc");
```

and get a struct (a type) with the data. Note that, the grid file can be any of several dozens formats that GMT can read automatically. For nc/hdf files with more complicated structures you'll have to consult the GMT manual (e.g. [here](http://gmt.soest.hawaii.edu/doc/latest/GMT_Docs.html#grid-file-format-specifications))

**Comment by Balinus** [comment]
Thanks for the information. Needing gmt is perhaps not a bad thing, as I could use this great library instead of developing something that would end up less functional. 

After the holidays, I'll llay with it and create a branch for that and see how it goes!

**Comment by joa-quim** [comment]
That's what I would do too.

Good holidays.

**Comment by Balinus** [comment]
Happy holidays to you too! 

I'll contact you if I have questions about this integration. 

Cheers!

**Comment by joa-quim** [comment]
Yes, sure.

**Comment by Balinus** [comment]
I do have a question popping in my head. 

Using GMT.jl, how easy it is to define a closed polygon and extract only the grid point(s) inside this polygon from a given netCDF file?

**Comment by joa-quim** [comment]
Two options:

1. Convert the grid to xyz with _grd2xyz_ and feed the points to _gmtselect_ (which will use your closed polygon)

2. Create a mask grid with your polygon and grdmask and multiply it by the grid. Convert the result to xyz again with _grd2xyz_.

First option is probably simpler. Tell me if this description is a bit to vague (should be enough if you are a GMT user)

**Comment by Balinus** [comment]
Thanks! Looked quickly at the GMT documentation. It looks like gmtselect will do just fine. 

I'm not a GMT user, but I think it will be useful for some of the objectives of ClimateTools.jl, namely the extraction of files (as we have just discussed), but also the visualisation objective. Maps with GMT are great, although the usual use of maps in my field is to project surface fields (like temperature) but leave out topographic details (keeping coastlines).

**Comment by joa-quim** [comment]
One little remind, if I may so. The 'G' in GMT stands for Generic, which means no discipline specific tools (topography, temperature, whatever). Just a (very powerful) map analysis and plotting set of tools.

**Comment by Balinus** [comment]
Indeed, it looks like a complete tool. 

I guess its also possible to concatenate (temporal dimension) multiple netCDF files (ideally over a specified polygon)? Climate simulations usually have multiples files for the whole time period (e. g. 12 files for 1961-2100). The analysis is usually done on complete time series (for convenience mostly).

**Comment by joa-quim** [comment]
No, actually we don't have that tool. I know what you mean because I also do it for SST series and I have a Matlab [tool ](http://w3.ualg.pt/~jluis/mirone/howtos/Make_a_stack_of_L2_MODIS_files.html) that does just that. 
I guess that GDAL should be able to do it at least partially (no polygon clipping, but not sure either). There is already a [GDAL.jl](https://github.com/wkearn/RasterIO.jl) and since with GMT installed you probably already have GDAL its Julia wrapper wouldn't need to install any more dependencies.
Otherwise another option would be the CDO operators or even the netcdf.jl but as I said, I have my own tool so not sure about these other options.

**Comment by Balinus** [comment]
Ok, thanks. Perhaps CDO is indeed the way to do it. Otherwise, I'll see what I can do using Julia and the types provided by GMT.jl or the other packages.

**Comment by Balinus** [comment]
I don't have much success importing netCDF files so far. I'm trying with CMIP5 global model simulations. Is that the right command to use if I want to specify "custom" grid ? Here, using "gd":

`G = gmt("read -Tg tasmax_day_MIROC5_historical_r3i1p1_19600101-19691231.nc=gd");`

**Comment by joa-quim** [comment]
```=gd``` forces the reading via the GDAL library but one normally do not need that.
If your command didn't return the grid it means that the nc file has a more complex structure that we (I) need to know. Please post the contents of

```
grdinfo tasmax_day_MIROC5_historical_r3i1p1_19600101-19691231.nc
and
gdalinfo grdinfo tasmax_day_MIROC5_historical_r3i1p1_19600101-19691231.nc
```
or, if you have a small example of that type of file that I can have access somewhere I can try it here.

**Comment by joa-quim** [comment]
Have a read on [this ](http://gmt.soest.hawaii.edu/doc/latest/GMT_Docs.html#modifiers-for-coards-compliant-netcdf-files)section of the manual

**Comment by Balinus** [comment]
```
julia> gmt("grdinfo tasmax_day_MIROC5_historical_r3i1p1_19600101-19691231.nc")
grdinfo (api_import_grid): NetCDF grid is not COARDS compliant [tasmax_day_MIROC5_historical_r3i1p1_19600101-19691231.nc]
[Session GMT (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
[Session GMT (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
[Session GMT (0)]: Error returned from GMT API: GMT_GRID_READ_ERROR (18)
------ ErrorException ------------------ Stacktrace (most recent call last)

 [1] — gmt(::String) at gmt_main.jl:217

Something went wrong when calling the module. GMT error number = 18
```


As for the other command, it work if I remove the grdinfo from the command (probably a typo). The output is rather large, I've posted it to [pastebin](http://pastebin.com/Y566tHJb). It's only part of the output as it was too large for pastebin.

**Comment by Balinus** [comment]
By specifying the variable, using this command, it seems to work:

`G = gmt("read -Tg tasmax_day_MIROC5_historical_r3i1p1_19600101-19691231.nc?tasmax")`

I'll explore the output

**Comment by joa-quim** [comment]
Fine, but that stack trace means it crashed and crashes are software bugs. Since it happened on the GMT side I really would like to have one of those grids that caused it because I need to fix this in GMT itself.

**Comment by joa-quim** [comment]
No sorry, have no place where you can drop but on a second thought I should be able to reproduce this with any multi-layer/multi-variable grid. If not I'll get back to this

And yes, the output is a grid type whose members are described in the GMT.jl git page.

**Comment by Balinus** [comment]
Thanks.

I could drop it in Dropbox if you want the file.

**Comment by joa-quim** [comment]
OK, that would be easier. But I don't have time to work at it in the immediate time.

**Comment by joa-quim** [comment]
OK, I gave it just a very quick try on the command line (i.e., no Julia just plain GMT) and got

```
grdinfo tasmax_day_MIROC5_historical_r3i1p1_19600101-19691231.nc
grdinfo (api_import_grid): NetCDF grid is not COARDS compliant [tasmax_day_MIROC5_historical_r3i1p1_19600101-19691231.nc]
Error returned from GMT API: GMT_GRID_READ_ERROR (18)
```

and when trying to load  it my soft that also used GDAL it prints

```
Warning 1: Latitude grid not spaced evenly.
```

which indeed I confirmed. GMT is not suited for non-homogeneous grids, though you may still import data from file using it.

BTW, you can remove the nc file from the Dropbox and get back those 300 Mb  of free space.

Cheers and Happy New Year

**Comment by argelouski** [comment]
Hey! I wanted to do some work on FNL data which comes on a grid format. I will be doing this for 15 years data so it is probably not a good idea to have two copies (i.e converting my grib data to NetCDF). Is there any update in this regard?

**Comment by Balinus** [comment]
Not at the moment. If you can point me to a file, I could take a look and see if I can code something up with it.

On the other hand, in the short-term, there is a lot of converter available such as:
https://www.unidata.ucar.edu/software/netcdf/workshops/2012/third_party/CDO.html

Cheers!

**Comment by Balinus** [comment]
In the short-term, I don't plan to support GRIB file. I'm postponing this for a 2.0 release.

**Comment by Balinus** [comment]
Closing this as I'm no expert on GRIB standard. Will re-open if someone wants to work on this.
