### ISSUE TITLE
Export options

### ISSUE THREAD

**Issue by Balinus** [Balinus/ClimateTools.jl#22]
- ~~Export ClimGrid to netCDF file~~
- Export ClimGrid to GeoTIFF/ASCII grid
- ~~Export Maps to PNG~~
- Export data of a ClimGrid to CSV

**Comment by Zeitsperre** [comment]
Export maps to PNG completed with https://github.com/Balinus/ClimateTools.jl/commit/72c7b694efe94251d7cbc35496a053abd26f3ccc

**Comment by Balinus** [comment]
Exporting to netCDF files should be easily handled by NCDatasets.jl

**Comment by Balinus** [comment]
We can now export ClimGrids to netCDF files. I think that for now, exporting options are enough for a basic usage: print maps and plots to png and export a ClimGrid to a netCDF file. 

As I do not have experience with GeoTIFF  and I don't think having a csv export option is necessary, I will close the issue now.
