### ISSUE TITLE
Switching to Cartopy - Deprecate Basemap

### ISSUE THREAD

**Issue by Balinus** [Balinus/ClimateTools.jl#66]
Basemap will soon be no longer supported. And it's also a mess with Python 3.6+. Once ClimateTools is splitted (ClimateTools/ClimateMaps), I strongly suggest we port the code to use Cartopy before adding any new features in ClimateMaps. 

Better yet would be to develop a strong support for PlotlyJS.jl. Maps are awesome, but this would involve unloading the projection part to GDAL.jl and then plot on PlotlyJS.jl.

**Comment by Zeitsperre** [comment]
Assigning myself to this but my time is a bit stretched. I'll help where I can.

**Comment by Balinus** [comment]
No worries, it's not a short-term objective! :)

**Comment by Balinus** [comment]
Found [GMT.jl](https://github.com/GenericMappingTools/GMT.jl). Might be a powerful library for mapping purpose and an alternative to Python dependency.

**Comment by Balinus** [comment]
Closing this in favor of https://github.com/Zeitsperre/ClimateMaps.jl/issues/2

The plan is to move all mapping features to ClimateMaps.jl
