### ISSUE TITLE
Load NC file fails though works with ncread()

### ISSUE THREAD

**Issue by njdepsky** [Balinus/ClimateTools.jl#91]
I'm getting a "NCDatasets.NetCDFError(-49, "NetCDF: Variable not found")" error when attempting to use ClimateTools.load() to load a .nc file.  The same file loads fine with the ncread() function from the NetCDF package.  I'm using julia v1.0. Thoughts?

**Comment by Balinus** [comment]
Reopening issue to keep track of this bug.

**Comment by Balinus** [comment]
Hello, I've pushed a fix on the `era5_fix` branch. Are you able to test it out? Meanwhile, I'll try to download some ERA5 files to see if it works, but it won't be before a couple of days.

Cheers!

**Comment by njdepsky** [comment]
Hi Phillipe,

Thanks for the quick reply!  As far as I can tell the load command is
getting hung up a bit further down now, now in the following section (needs
to account for "regular" grids also having latname and lonname of
"latitude" and "longitude":
if latname != "lat" && lonname != "lon" # means we don't have a "regular"
grid
latgrid = NetCDF.ncread(file, "lat")
longrid = NetCDF.ncread(file, "lon")
if ClimateTools.@isdefined varattrib["grid_mapping"]
map_dim = varattrib["grid_mapping"]
map_attrib = Dict(ds[map_dim].attrib)
map_attrib["grid_mapping"] = map_dim
else
error("File an issue on https://github.com/Balinus/ClimateTools.jl/issues
to get the grid supported")
end
else # if no grid provided, create one
longrid, latgrid = ndgrid(lon_raw, lat_raw)
map_attrib = Dict(["grid_mapping" => "Regular_longitude_latitude"])
end


There are also going to be issues with the definition of the "timeV"
variable
timeV = ds["time"][:]
with the following error message:
ERROR: ArgumentError: invalid base 10 digit '.' in "00.0"

This is because the ERA5 nc files annoyingly have decimal seconds in there
time:units attribute value ["hours since 1900-01-01 00:00:00.0"] instead of
simply ["hours since 1900-01-01 00:00:00"].  Not sure the best way to
remedy this.  One option is to just rename all the attributes (and
variables names to "lat" "lon") before importing to julia/ClimateTools
using NCO tools but I assume you want to make the package compatible with
off-the-shelf ERA5 downloads.  Keep me posted.

All the best,
Nick

**Comment by Balinus** [comment]
Thanks for all the details! Indeed, the objective is definitely to support such common product (ERA, CMIP5/6, CORDEX, etc).

I will download an ERA5 file and work it out. Do you know if they are all the same for dimension naming and the decimal time attribute?

**Comment by njdepsky** [comment]
Unfortunately I'm not sure, but all of the "total precipitation" test files
I've downloaded seem to be.  I've tried different times/days/months/years
of that variable and all match that format.

**Comment by Balinus** [comment]
I've updated the code in the `era5_fix` branch. I'm now able to load ERA5 files (tested against temperature files). I'll tag a release as soon as upstream version of NCDatasets is tagged. In other words, as of right now, it works with the master version of NCDatasets. See https://github.com/Alexander-Barth/NCDatasets.jl/issues/24

**Comment by Balinus** [comment]
Fixed now in master. Will tag a release soon (v0.12.0).

**Comment by njdepsky** [comment]
Awesome!
